### ISSUE TITLE
Single task checkpoint and computation resource requirement

### ISSUE THREAD

**Issue by xc720** [markusgrotz/peract_bimanual#18]
Hi,

May I ask if you would kindly share checkpoints of single tasks? And would one single 3090 gpu 24GB be enough for single task training as I was trying to train a single task but got CUDA out of memory error?

Thanks!

**Comment by markusgrotz** [comment]
Hi,

Thank you for your interest. 

I have been working on some multi-task training and was caught up in other tasks, but I hope I can finish the training soon and share weight. 

A single 3090 would probably take a while and you also want to increase the batch size. I recommend working with the 128x128 images as less GPU memory is required. Are you running out of GPU memory here as well?  Additionally, try to reduce the voxel size to make the training faster.  

Let me know if you need further guidance!

**Comment by xc720** [comment]
Hi,

Thanks for your detailed reply. I tried to set the parameters according to your suggestion. And it worked on 2 empty 24GB 3090. 

Thank you!

**Comment by markusgrotz** [comment]
FYI I uploaded some weights for multi task training. See #20
